const mockCards = [
    {
  title: 'fhfhhfh hdhdhj sjjsjk',
  isHit: true,
  isNew: false,
  isCompare: false,
  isFavorite: true,
  oldPrice: 2672727,
  currentPrice: 626626,
  isOnCart: true,
  params: {
    accamulator: 2,
    speed: 3,
    power: 4,
    time: 5,
  },
},
    {
  title: 'jjgjksklslsl sjksjsks kskkskkskkskskksksksnxamnskjd',
  isHit: true,
  isNew: false,
  isCompare: false,
  isFavorite: true,
  oldPrice: 2672727,
  currentPrice: 626626,
  isOnCart: true,
  params: {
    accamulator: 2,
    speed: 3,
    power: 4,
    time: 5,
  },
},
    {
  title: 'fccfnnc djjjjjjjjj 444k',
  isHit: false,
  isNew: true,
  isCompare: false,
  isFavorite: true,
  oldPrice: 2672727,
  currentPrice: 626626,
  isOnCart: false,
  params: {
    accamulator: 2,
    speed: 3,
    power: 4,
    time: 5,
  },
},
    {
  title: 'fhfhhfh hdhdhj sjjsjk',
  isHit: false,
  isNew: false,
  isCompare: false,
  isFavorite: true,
  oldPrice: 2672727,
  currentPrice: 626626,
  isOnCart: false,
  params: {
    accamulator: 2,
    speed: 3,
    power: 4,
    time: 5,
  },
},
    {
  title: 'fhfhhfh hdhdhj sjjsjk',
  isHit: false,
  isNew: false,
  isCompare: true,
  isFavorite: true,
  oldPrice: 2672727,
  currentPrice: 626626,
  isOnCart: false,
  params: {
    accamulator: 2,
    speed: 3,
    power: 4,
    time: 5,
  },
},
    {
  title: 'fhfhhfh hdhdhj sjjsjk',
  isHit: false,
  isNew: true,
  isCompare: false,
  isFavorite: true,
  oldPrice: 2672727,
  currentPrice: 626626,
  isOnCart: false,
  params: {
    accamulator: 2,
    speed: 3,
    power: 4,
    time: 5,
  },
},     {
  title: 'fhfhhfh hdhdhj sjjsjk',
  isHit: false,
  isNew: true,
  isCompare: true,
  isFavorite: true,
  oldPrice: 2672727,
  currentPrice: 626626,
  isOnCart: false,
  params: {
    accamulator: 2,
    speed: 3,
    power: 4,
    time: 5,
  },
},     {
  title: 'fhfhhfh hdhdhj sjjsjk',
  isHit: false,
  isNew: true,
  isCompare: false,
  isFavorite: true,
  oldPrice: 2672727,
  currentPrice: 626626,
  isOnCart: false,
  params: {
    accamulator: 2,
    speed: 3,
    power: 4,
    time: 5,
  },
},     {
  title: 'fhfhhfh hdhdhj sjjsjk',
  isHit: true,
  isNew: true,
  isCompare: true,
  isFavorite: true,
  oldPrice: 2672727,
  currentPrice: 626626,
  isOnCart: false,
  params: {
    accamulator: 2,
    speed: 3,
    power: 4,
    time: 5,
  },
}
]

export default mockCards